# Generated by Django 6.0.1 on 2026-01-13 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_photos/'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
